package lexer;

public enum TokenType {
    PROGRAM, DECLARATIONS, END_DECLARATIONS,
    FUNCTIONS, END_FUNCTIONS, END_PROGRAM,
    VARTYPE, FUNCTYPE, PARAMTYPE,
    IF, ELSE, ENDIF, WHILE, ENDWHILE,
    RETURN, BREAK, PRINT,

    // Tipos
    REAL, INTEGER, STRING, BOOLEAN, CHARACTER, VOID,

    // Operadores
    ASSIGN, // :=
    ADD, SUB, MUL, DIV, MOD,
    LT, GT, LE, GE, EQ, NEQ,
    COMMA, SEMICOLON, COLON,
    LBRACKET, RBRACKET, LPAREN, RPAREN, LBRACE, RBRACE,

    // Identificadores e valores
    IDENTIFIER, INT_CONST, REAL_CONST, STRING_CONST, CHAR_CONST, TRUE, FALSE,

    // Outros
    EOF,
}
